
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START anthos_config_management_anthos_config_management_samples_ci_pipeline_yaml_cloudbuild]
steps:
- args:
  - config
  - current-context
  env:
  - KUBECONFIG=/kube/config
  - CLOUDSDK_COMPUTE_ZONE=ZONE
  - CLOUDSDK_CONTAINER_CLUSTER=CLUSTER_NAME
  - CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true
  name: gcr.io/cloud-builders/kubectl
  volumes:
  - name: kube
    path: /kube
- args:
  - chmod
  - '644'
  - /kube/config
  name: bash
  volumes:
  - name: kube
    path: /kube
- args:
  - chmod
  - '777'
  - /workspace
  name: bash
- args:
  - nomos
  - hydrate
  - --path
  - /workspace/ci-pipeline/config-root
  - --output
  - /workspace/hydrated-configs
  env:
  - KUBECONFIG=/kube/config
  name: gcr.io/config-management-release/nomos
  volumes:
  - name: kube
    path: /kube
- args:
  - --input
  - /dev/null
  - -d
  - source_dir=/workspace/hydrated-configs
  - --output
  - /workspace/config-source.yaml
  name: gcr.io/config-management-release/read-yaml
- args:
  - --input
  - /workspace/config-source.yaml
  name: gcr.io/config-management-release/policy-controller-validate
# [END anthos_config_management_anthos_config_management_samples_ci_pipeline_yaml_cloudbuild]
---
