apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-0119-deploy
  namespace: demo-02
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-server
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: test-0119-svc
  namespace: demo-02
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
