apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/GoogleCloudPlatform/anthos-service-mesh-samples/docs/asm-installation-manifests/with-strict-mtls?ref=main
namespace: istio-system