apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    cluster: cluster-east
    owner: platform-team
  name: hard-limit
  namespace: tenant-b
spec:
  hard:
    cpu: "100"
    memory: 10Gi
    pods: "10"
