# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START anthosconfig_namespace_inheritance_compiled_analytics_resource_quota] 
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/namespace-selector: analytics-selector
    configmanagement.gke.io/source-path: config/namespaces/eng/quota.yaml
    configsync.gke.io/declared-fields: '{"f:metadata":{"f:annotations":{"f:configmanagement.gke.io/namespace-selector":{}}},"f:spec":{"f:hard":{"f:cpu":{},"f:memory":{},"f:pods":{}}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: quota
  namespace: analytics
spec:
  hard:
    cpu: 100m
    memory: 100Mi
    pods: "1"
# [END anthosconfig_namespace_inheritance_compiled_analytics_resource_quota] 
