name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - name: install cloud-build-local
        run: |
          gcloud components install cloud-build-local --quiet
      - name: cloud-build-local	
        run: |
          cd ci-app/app-repo
          cloud-build-local --dryrun=false .
