# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START anthosconfig_multi_cluster_fanout_tenant_a_namespace] 
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: platform-team
  name: tenant-a
# [END anthosconfig_multi_cluster_fanout_tenant_a_namespace] 
---
# [START anthosconfig_multi_cluster_fanout_tenant_b_namespace] 
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: platform-team
  name: tenant-b
# [END anthosconfig_multi_cluster_fanout_tenant_b_namespace] 
---
# [START anthosconfig_multi_cluster_fanout_tenant_c_namespace] 
apiVersion: v1
kind: Namespace
metadata:
  labels:
    owner: platform-team
  name: tenant-c
# [END anthosconfig_multi_cluster_fanout_tenant_c_namespace] 
